### ISSUE TITLE
The deployed jar misses common resources when building with Windows

### ISSUE THREAD

**Issue by samorganist** [keycloakify/keycloakify#433]
Hi , when building with yarn yarn build-keycloak-theme, the jar is missing some files , the issue comes from the Templates:
```
        "styles": [
            `${url.resourcesCommonPath}/node_modules/patternfly/dist/css/patternfly.min.css`,
            `${url.resourcesCommonPath}/node_modules/patternfly/dist/css/patternfly-additions.min.css`,
            `${url.resourcesCommonPath}/lib/zocial/zocial.css`,
            `${url.resourcesPath}/css/login.css`
        ],
```
All the files in url.resourcesCommonPath are not in the jar neither in `.\build_keycloak\src\main\resources\theme\keycloakify-starter`
getting 404 Not Found error on the files like this : 
`/resources/6cjib/login/keycloakify-starter/resources_common/node_modules/patternfly/dist/css/patternfly-additions.min.css`
I tested this in the main branch.

**Comment by garronej** [comment]
Hello @samorganist,  

I'm pretty sure this has been fixed.  
Make sure you are using the latest version of Keycloakify, try deleting your node_modules and public/keycloak-resources directory.  

The latest version of Keycloakify starter is deployed here: https://starter.keycloakify.dev/  
You can check when clicking login, the Keycloak assets are included.

**Comment by samorganist** [comment]
Hi @garronej ,
I think i'm not building like you, i'm using this command:
`yarn install && yarn build-keycloak-theme` is that correct?
i deleted  node_modules and public/keycloak-resources as you mentioned  on keycloakify-start 4.7.3 using keycloakify 8.1.3, but still having a jar that don't contains assets.

**Comment by garronej** [comment]
What os are you using? What node version? What yarn version? Have you changed anything in the starter?

**Comment by samorganist** [comment]
i'm using node v16.17.1 and yarn 1.22.19, i didn't change anything in the starter.

**Comment by garronej** [comment]
What OS are you using? Window, Linux, OSX?

**Comment by garronej** [comment]
Here is the JAR I just build with:  
- yarn v1.22.19
- node v16.20.2  

I just cloned the starter and `yarn && yarn build-keycloak-theme`  

https://filedn.com/lYPEPucNMheV19aDu23lK0Q/misc/keycloakify-starter-keycloak-theme-4.7.3.jar  

Let me know if it work.

**Comment by samorganist** [comment]
I was using windows without Cgwin, Just tested this on ubuntu with node  **v16.17.1** it works fine , the problem i think it comes from the OS, on windows common resources are not bundled.
I have tried also with **Cgwin** it dosent work with the same versions.

**Comment by garronej** [comment]
Ok, that what I though.  
I'll fix the build on window, in the meantime you can use WSL

**Comment by samorganist** [comment]
Thank you, that's what i'm using , any way my build machine is on linux so the deployment will be good.
Nice job for the library by the way 👍 , saves a lot of time for keycloak customization.

**Comment by garronej** [comment]
@samorganist, thanks a lot for the kind word and sorry for the bad experience on Windows.  
We try to make Keycloakify be platform agnostic but as I only work with POSIX machines I sometime forget that `/` isn't the path separator on Windows.

**Comment by garronej** [comment]
Build on windows are fixed in v8.2.1. Thanks for reporting
